var s_name, s_n;
s_name = argument0;
ini_open("data.ini");
s_n = ini_read_real("Gamers", "Num", 0);
ini_write_real("Gamers", "Num", s_n + 1);
ini_write_string("Gamers", "Gamer" + string(s_n), s_name);
ini_write_string(s_name, "Password", "qwerty");
ini_write_real(s_name, "image_angle", 0);
ini_write_real(s_name, "x", random_range(4000, 6000));
ini_write_real(s_name, "y", random_range(4000, 6000));
ini_write_real(s_name, "shell_type", SMALL);
ini_write_real(s_name, "shell_mass", 100);
ini_write_real(s_name, "shell_hp", 30);
ini_write_real(s_name, "shell_signature", 20);
ini_write_real(s_name, "shell_hold", 40);
ini_write_real(s_name, "shell_lifesupporting", 20);
ini_write_real(s_name, "engine_type", SMALL);
ini_write_real(s_name, "engine_fuel", TYPE_FUEL_1);
ini_write_real(s_name, "engine_trace", 20);
ini_write_real(s_name, "engine_thrust", 5);
ini_write_real(s_name, "engine_fuelconsumpton", 1);
ini_write_real(s_name, "engine_speedparticles", 5);
ini_write_real(s_name, "engine_maneuverability", 30);
ini_write_real(s_name, "engine_reliability", 100);
ini_write_real(s_name, "passivearmor_hp", 10);
ini_write_real(s_name, "passivearmor_mass", 10);
ini_write_real(s_name, "activearmor", 0);
ini_write_real(s_name, "weapon_range", 30);
ini_write_real(s_name, "weapon_damage", 5);
ini_write_real(s_name, "weapon_rate", 1);
ini_write_real(s_name, "weapon_accuracy", 20);
ini_write_real(s_name, "power_capacity", 100);
ini_write_real(s_name, "radar_distance", 1000);
ini_write_real(s_name, "radar_closedistance", 100);
ini_write_real(s_name, "optics_distance", 100);
ini_close();
