var scr_ship = argument0;
var sct = argument1;
buffer_seek(Buffer , buffer_seek_start , 0 );
buffer_write(Buffer, buffer_u8, NET_ALL_DATA);
buffer_write(Buffer, buffer_s32, scr_ship.pl_id);
buffer_write(Buffer, buffer_u8, scr_ship.shell_type);
buffer_write(Buffer, buffer_u16, scr_ship.shell_mass);
buffer_write(Buffer, buffer_u16, scr_ship.shell_hp);
buffer_write(Buffer, buffer_u16, scr_ship.shell_signature);
buffer_write(Buffer, buffer_u16, scr_ship.shell_hold);
buffer_write(Buffer, buffer_u8, scr_ship.shell_lifesupporting);
buffer_write(Buffer, buffer_u8, scr_ship.engine_type);
buffer_write(Buffer, buffer_u8, scr_ship.engine_fuel);
buffer_write(Buffer, buffer_u8, scr_ship.engine_trace);
buffer_write(Buffer, buffer_f32, scr_ship.engine_thrust);
buffer_write(Buffer, buffer_f32, scr_ship.engine_fuelconsumpton);
buffer_write(Buffer, buffer_u8, scr_ship.engine_speedparticles);
buffer_write(Buffer, buffer_f32, scr_ship.engine_maneuverability);
buffer_write(Buffer, buffer_u8, scr_ship.engine_reliability);
buffer_write(Buffer, buffer_u16, scr_ship.passivearmor_hp);
buffer_write(Buffer, buffer_u16, scr_ship.passivearmor_mass);
buffer_write(Buffer, buffer_u8, scr_ship.activearmor);
buffer_write(Buffer, buffer_u16, scr_ship.weapon_range);
buffer_write(Buffer, buffer_u16, scr_ship.weapon_damage);
buffer_write(Buffer, buffer_f32, scr_ship.weapon_rate);
buffer_write(Buffer, buffer_u8, scr_ship.weapon_accuracy);
buffer_write(Buffer, buffer_u8, scr_ship.power_capacity);
buffer_write(Buffer, buffer_u16, scr_ship.radar_distance);
buffer_write(Buffer, buffer_u16, scr_ship.radar_closedistance);
buffer_write(Buffer, buffer_u16, scr_ship.optics_distance);
network_send_packet( sct , Buffer , buffer_tell( Buffer ) );
